### ISSUE TITLE
Add docker-compose file

### ISSUE THREAD

**Issue by sadikkuzu** [sadikkuzu/sadikkuzu.github.io#4]
in order to preview in local dev env

```yaml
version: '3'
services:
  jekyll:
    image: starefossen/github-pages
    ports:
      - "4000:4000"
    volumes:
      - ./:/usr/src/app
    tty: true
```

---

```
docker-compose up -d
```

```
open http://localhost:4000
```

```
docker-compose down
```
